// Code generated by protoc-gen-go.
// source: users.proto
// DO NOT EDIT!

/*
Package serialization is a generated protocol buffer package.

It is generated from these files:
	users.proto

It has these top-level messages:
	Catalog
*/
package serialization

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Catalog struct {
	Users map[string]*Catalog_User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Catalog) Reset()         { *m = Catalog{} }
func (m *Catalog) String() string { return proto.CompactTextString(m) }
func (*Catalog) ProtoMessage()    {}

func (m *Catalog) GetUsers() map[string]*Catalog_User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Catalog_User struct {
	UserId   string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *Catalog_User) Reset()         { *m = Catalog_User{} }
func (m *Catalog_User) String() string { return proto.CompactTextString(m) }
func (*Catalog_User) ProtoMessage()    {}
